In [14]:
import numpy as np
def transpose_matrix(matrix):
    matrix=np.array(matrix)
    return matrix.transpose()

In [15]:
transpose_matrix([
  [1, 1, 1],
  [2, 2, 2],
  [3, 3, 3]
]) 

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [16]:
transpose_matrix([
  [5, 5],
  [6, 7],
  [9, 1]
]) 

array([[5, 6, 9],
       [5, 7, 1]])

In [7]:
a.transpose()

array([[5, 6, 9],
       [5, 7, 1]])

In [42]:
def is_valid_hex_code(string):
    flag=True
    for ele in string:
        if ele.lower() not in "#abcdef0123456789" or len(string)!=7:
            flag=False
    return flag        

In [43]:
is_valid_hex_code("#CD5C5C")

True

In [44]:
is_valid_hex_code("#EAECEE")

True

In [45]:
is_valid_hex_code("#eaecee") 

True

In [46]:
is_valid_hex_code("#CD5C58C") 

False

In [47]:
is_valid_hex_code("#CD5C5Z")

False

In [49]:
is_valid_hex_code("#CD5C&C") 

False

In [48]:
is_valid_hex_code("#CD5C&C") 

False

In [50]:
is_valid_hex_code("CD5C5C")

False

In [68]:
def mark_maths(lst):
    percentage=0
    l=len(lst)/100
    for ele in lst:
        ele=ele.split("=")
        if eval(ele[0])==int(ele[1]):
            percentage=percentage+100/len(lst)
    return round(percentage )       
            
            

In [69]:
mark_maths(["2+2=4", "3+2=5", "10-3=3", "5+5=10"]) 

75

In [70]:
mark_maths(["1-2=-2"])

0

In [71]:
mark_maths(["2+3=5", "4+4=9", "3-1=2"]) 

67

In [98]:
def magic_square_game(l1,l2):
    flag=False
    if l2[1][l1[0]-1]==l1[1][l2[0]-1]:
        flag=True
    return flag     

In [99]:
magic_square_game([2, "100"], [1, "101"]) 

False

In [100]:
magic_square_game([2, "001"], [1, "101"]) 

True

In [101]:
magic_square_game([3, "111"], [2, "011"])

True

In [102]:
magic_square_game([1, "010"], [3, "101"]) 

False

In [118]:
import math as m
def lets_meet(d,va,vb):
    time=d/(va+vb)
    hours=m.floor(time)
    minutes=m.floor((time-hours)*60)
    seconds=m.floor(((time-hours)*60-minutes)*60)
    return str(hours)+'h'+' '+str(minutes)+'min'+" "+str(seconds)+'s'
    

In [119]:
lets_meet(100, 10, 30) 

'2h 30min 0s'

In [120]:
lets_meet(280, 70, 80) 

'1h 52min 0s'

In [121]:
lets_meet(90, 75, 65)

'0h 38min 34s'